name: Update README with Latest Repos

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest repos and update README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'Agostinejohn';
            const { data: repos } = await github.rest.repos.listForUser({
              username,
              sort: 'updated',
              per_page: 5
            });

            const fs = require('fs');
            const readmePath = './README.md';
            let readme = fs.readFileSync(readmePath, 'utf-8');

            const newSection = repos.map(repo => {
              return `| [**${repo.name}**](${repo.html_url}) | ${repo.description || "No description"} | ${new Date(repo.updated_at).toDateString()} |`;
            }).join('\n');

            const pattern = /<!--LATEST-REPOS-START-->([\s\S]*?)<!--LATEST-REPOS-END-->/;
            readme = readme.replace(pattern, `<!--LATEST-REPOS-START-->\n${newSection}\n<!--LATEST-REPOS-END-->`);

            fs.writeFileSync(readmePath, readme);
            
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "🤖 Updated README with latest repos"
          git push
